### ISSUE TITLE
Multiple editors

### ISSUE THREAD

**Issue by jamesaoverton** [knotation/fiddle.knotation.org#1]
The main view should be split into Left and Right, as it currently is. Both Left and Right will have multiple panes. The panes will be controlled by an HTML `select` element at the top of the pane (full width). The Left panes will be editable and the Right panes will read-only.

Left:
- Context: Knotation editor
- Content: Knotation editor, default

Right:
- About: HTML information
- Help (?): HTML context sensitive help
- Knotation: CodeMirror editor with Knotation output, read-only; this view will have expanded templates
- Turtle: CodeMirror editor with Turtle output, read-only, default
- RDFa: HTML view
- RDFa Source: CodeMirror editor with RDFa output, read-only
- NQuads: CodeMirror editor with NQuads output, read-only

The Right views only need to be updated when they're visible. All the right views will have the same input: prefixes from Context and everything from Content.

**Comment by jamesaoverton** [comment]
This is the first pass at templates: https://github.com/knotation/knotation-cljc/commit/e89679001cc26d2a9d104574a5137901fee2f959

**Comment by jamesaoverton** [comment]
On the Right we should also have:

- Tree: HTML [Bootstrap Treeview](https://github.com/jonmiles/bootstrap-treeview) (from CLJSJS) with tree.json output

First pass at tree.json output: https://github.com/knotation/knotation-cljc/commit/a6fe0753f100c2eaa0d4a4e84f9e7c236bd4400d

**Comment by jamesaoverton** [comment]
The work in #4 is excellent. Unfortunately we're running out of space for tabs. For the Right, please use a select element (dropdown menu) instead.

**Comment by jamesaoverton** [comment]
I merged #4. We still need a select element instead of tabs on the Right.

**Comment by inaimathi** [comment]
Updated a separate PR to address the last of this at https://github.com/knotation/fiddle.knotation.org/pull/7
